"""empty message

Revision ID: 5038dbe0364c
Revises: 641d444f8a43
Create Date: 2024-01-22 17:46:06.177804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5038dbe0364c'
down_revision: Union[str, None] = '641d444f8a43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_chats', sa.Column('img_url1', sa.Text(), nullable=True))
    op.add_column('all_chats', sa.Column('img_url2', sa.Text(), nullable=True))
    op.add_column('all_chats', sa.Column('img_url3', sa.Text(), nullable=True))
    op.add_column('all_chats', sa.Column('img_url4', sa.Text(), nullable=True))
    op.drop_column('responses', 'img_url3')
    op.drop_column('responses', 'img_url2')
    op.drop_column('responses', 'img_url1')
    op.drop_column('responses', 'img_url4')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('img_url4', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column('img_url1', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column('img_url2', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('responses', sa.Column('img_url3', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('all_chats', 'img_url4')
    op.drop_column('all_chats', 'img_url3')
    op.drop_column('all_chats', 'img_url2')
    op.drop_column('all_chats', 'img_url1')
    # ### end Alembic commands ###
